FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
# Takes the JAR built by the build pipeline and copies it into the container
COPY target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]