@startuml
' --- Configurazione Stile ---
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam packageStyle rectangle

' ===========================================

' --- ENUMS ---

package "Enums" {
    enum roleEnum {
        ADMIN
        USER
        GUEST
    }


    enum typeEnum {
        BUG
        FEATURE
        QUESTION
        DOCUMENTATION
    }

    enum priorityEnum {
        LOWEST
        LOW
        MEDIUM
        HIGH
        HIGHEST
    }
}

' --- CONTROLLER LAYER ---
package "Controller Layer (Interface)" {

    class AuthController {
        + login(request: LoginDTO): ResponseEntity
    }

    class ProjectController {
        + getProjects(): ResponseEntity
    }

    class IssueController {
        + createIssue(request: IssueDTO): ResponseEntity
    }

    class ReportController {
        + generateReport(projectId: int): ResponseEntity
    }

    class TagController {
        + createTag(request: TagDTO): ResponseEntity
    }

    class AttachmentController {
        + uploadAttachment(issueId: int, file: MultipartFile): ResponseEntity
    }


}

' --- SERVICE LAYER ---
package "Service Layer (Business Logic)" {

    class UserService {
    }

    class ProjectService {
    }

    class IssueService {
        + exportIssues(format: String): String
    }

    class ReportService {
    }

    class TagService {
    }

    class AttachmentService {
    }

    interface IssueExportStrategy <<interface>> {
        + export(issues: List<Issue>): String
    }

    class CSVExportStrategy implements IssueExportStrategy {
        + export(issues: List<Issue>): String
    }

    class JSONExportStrategy implements IssueExportStrategy {
        + export(issues: List<Issue>): String
    }
}



' --- REPOSITORY LAYER ---
package "Repository Layer (Data Access)" {
    interface JpaRepository <<Spring Data Base>> {
    }

    interface UserRepository <<interface>>
    interface ProjectRepository <<interface>>
    interface IssueRepository <<interface>>
    interface TagRepository <<interface>>
    interface AttachmentRepository <<interface>>
}

' --- ENTITY LAYER ---
package "Entity Layer (Data Model)" {
    class User {
        - id: Integer
        - username: String
        - email: String
        - passwordHash: String
        - role: RoleEnum
    }

    class Project {
        - id: Integer
        - name: String
        - description: String
        - createdAt: Timestamp
    }

    class Issue {
        - id: Integer
        - title: String
        - description: String
        - priority: PriorityEnum
        - type: TypeEnum
        - createdAt: Timestamp
        - updatedAt: Timestamp
        - assignedTo: User


        + assign(user: User): void
        + startProgress(): void
        + markForReview(): void
        + accept(): void
        + reject(): void
        + close(): void
    }

    interface Status {
        + getName(): String
        + previousStatus(): Status
        + assign(issue: Issue, user: User): void
        + startProgress(issue: Issue): void
        + markForReview(issue: Issue): void
        + accept(issue: Issue): void
        + reject(issue: Issue): void
        + close(issue: Issue): void
    }

    abstract class BaseStatus implements Status {
        + assign(issue: Issue, user: User): void
        + startProgress(issue: Issue): void
        + markForReview(issue: Issue): void
        + accept(issue: Issue): void
        + reject(issue: Issue): void
        + close(issue: Issue): void
    }

    class ToBeAssigned extends BaseStatus {
        + assign(issue: Issue, user: User): void
        + close(issue: Issue): void
    }

    class Assigned extends BaseStatus {
        + startProgress(issue: Issue): void
        + close(issue: Issue): void
        - removeAssignee(issue: Issue): void
    }

    class InProgress extends BaseStatus {
        + markForReview(issue: Issue): void
        + close(issue: Issue): void
    }

    class MarkedForReview extends BaseStatus {
        + accept(issue: Issue): void
        + reject(issue: Issue): void
        + close(issue: Issue): void
    }

    class NotFixed extends BaseStatus {
        + startProgress(issue: Issue): void
        + close(issue: Issue): void
        - removeAssignee(issue: Issue): void
    }

    class Completed extends BaseStatus {
    }

    class Closed extends BaseStatus {
    }

    class Tag {
        - id: Integer
        - name: String
        - color: String
    }

    class Attachment {
        - id: Integer
        - filePath: String
        - fileName: String
        - fileSize: Integer
        - fileExtension: String
    }

    class ProjectReport {
        - id: Integer
        - averageResolutionTime: Double
    }

    class MonthlyProjectReport extends ProjectReport {
        - referenceMonth: Integer
        - referenceYear: Integer
    }

    class UserMonthlyProjectReport extends MonthlyProjectReport {
    }
}

' ===========================================
' DTO LAYER (Data Transfer Objects)
' TODO: SISTEMARE IN CASO DI MODIFICHE/AGGIUNTE LATO CODICE
' ===========================================

package "DTO Layer (Data Transfer Objects)" {
    class LoginDTO {
        - email: String
        - password: String
    }

    class RegisterDTO {
        - username: String
        - email: String
        - password: String
        - role : RoleEnum
    }

    class IssueDTO {
        - projectId: Integer
        - title: String
        - description: String
        - status: StatusEnum
        - priority: PriorityEnum
        - type: TypeEnum
        - attachmentIds: List<Integer>
        - assignedToUser: String
    }

    'TODO: SISTEMARE QUESTO DTO
    class TagDTO {
        - id: Integer
        - name: String
        - color: String
    }

    class AttachmentDTO {
        - issueId: Integer
        - filePath: String
        - fileName: String
        - fileExtension: String
        - fileSize: Integer
    }

    class ProjectMonthlyReportDTO {
        - projectId: Integer
        - projectName: String
        - referenceMonth: Integer
        - referenceYear: Integer
        - openedBugs: Integer
        - managedBugs: Integer
        - averageResolutionTime: Double
        - userMonthlyReports: List<UserMonthlyReportMetricDTO>
    }

    class UserMonthlyReportMetricDTO {
        - userId: Integer
        - userName: String
        - referenceMonth: Integer
        - referenceYear: Integer
        - openedBugs: Integer
        - managedBugs: Integer
        - averageResolutionTime: Double
    }

    class MonthlyProjectReportDTO {

    }
}

' ==========================================
' RELAZIONI TRA I LIVELLI (Top-Down)
' ==========================================

' Controllers usano Services
AuthController --> UserService : - userService
ProjectController --> ProjectService : - projectService
IssueController --> IssueService : - issueService
AttachmentController --> AttachmentService : - attachmentService
TagController --> TagService : - tagService
ReportController --> ReportService : - reportService

' Services usano Repositories
UserService --> UserRepository : - userRepository
ProjectService --> ProjectRepository : - projectRepository
IssueService --> IssueRepository : - issueRepository
IssueService --> TagRepository : - tagRepository
IssueService o-- IssueExportStrategy : - strategy
AttachmentService --> AttachmentRepository : - attachmentRepository
TagService --> TagRepository : - tagRepository

' Repositories estendono JpaRepository
JpaRepository <|-- UserRepository
JpaRepository <|-- ProjectRepository
JpaRepository <|-- IssueRepository
JpaRepository <|-- TagRepository
JpaRepository <|-- AttachmentRepository

' Repositories gestiscono Entities
UserRepository --> User : gestisce
ProjectRepository --> Project : gestisce
IssueRepository --> Issue : gestisce
TagRepository --> Tag : gestisce
AttachmentRepository --> Attachment : gestisce


' ==========================================
' RELAZIONI TRA LE ENTITÀ (Database)
' ==========================================

' User <-> Project (Molti a Molti)
User "*" -- "*" Project : partecipazione

' Project <-> Issue (1 a Molti)
Project "1" *-- "*" Issue : - issues

' User <-> Issue (1 a Molti)
User "1" -- "*" Issue : assegnazione

' Project <-> Tag (1 a Molti)
Project "1" *-- "*" Tag : - tags

' Tag <-> Issue (Molti a Molti)
Tag "*" -- "*" Issue : associazione

' Issue <-> Attachment (1 a Molti)
Issue "1" *-- "*" Attachment : - attachment

' User <-> UserMonthlyProjectReport (Molti a 1)
UserMonthlyProjectReport *-- "1" User : - user

' Project <-> ProjectReport (1 a 1)
ProjectReport *-- "1" Project : - project

' Relazione: Aggregazione (lo stato cambia dinamicamente)
Issue o-- "1" Status : - status


' ==========================================
' RELAZIONE ENTITY - SERVICES (Business Logic)
' ==========================================
ReportService --> MonthlyProjectReport : genera
ReportService --> UserMonthlyProjectReport : genera

' ==========================================
' RELAZIONI DI DIPENDENZA (USO DEI DTO)
' ==========================================
' I Controller ricevono o restituiscono DTO
AuthController ..> LoginDTO : riceve
IssueController ..> IssueDTO : riceve/restituisce
ReportController ..> MonthlyProjectReportDTO : restituisce


@enduml