@startuml

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam packageStyle rectangle

class Issue {
    - id: Integer
    - title: String
    - description: String
    - priority: PriorityEnum
    - type: TypeEnum
    - createdAt: Timestamp
    - updatedAt: Timestamp
    - assignedTo: User    


    + assign(user: User): void
    + startProgress(): void
    + markForReview(): void
    + accept(): void
    + reject(): void
    + close(): void
}

interface Status {
    + getName(): String
    + previousStatus(): Status
    + assign(issue: Issue, user: User): void
    + startProgress(issue: Issue): void
    + markForReview(issue: Issue): void
    + accept(issue: Issue): void
    + reject(issue: Issue): void
    + close(issue: Issue): void
}

abstract class BaseStatus implements Status {
    + assign(issue: Issue, user: User): void
    + startProgress(issue: Issue): void
    + markForReview(issue: Issue): void
    + accept(issue: Issue): void
    + reject(issue: Issue): void
    + close(issue: Issue): void
}

class ToBeAssigned extends BaseStatus {
    + assign(issue: Issue, user: User): void
    + close(issue: Issue): void
}

class Assigned extends BaseStatus {
    + startProgress(issue: Issue): void
    + close(issue: Issue): void
    - removeAssignee(issue: Issue): void
}

class InProgress extends BaseStatus {
    + markForReview(issue: Issue): void
    + close(issue: Issue): void
}

class MarkedForReview extends BaseStatus {
    + accept(issue: Issue): void
    + reject(issue: Issue): void
    + close(issue: Issue): void
}

class NotFixed extends BaseStatus {
    + assign(issue: Issue, user: User): void
    + close(issue: Issue): void
}

class Completed extends BaseStatus {
}

class Closed extends BaseStatus {
}

' Relazione: Aggregazione (lo stato cambia dinamicamente)
Issue o-- "1" Status : - status

@enduml