@startuml
skinparam actorStyle stickman
skinparam linetype ortho
left to right direction

' Definizione Attori
actor "Guest" as G <<Stakeholder>>
actor "Utente" as U
actor "Admin" as A

' Gerarchia degli Attori
' L'Utente eredita i permessi di lettura dal Guest
' L'Admin eredita tutto dall'Utente
U -up-|> G
A -down-|> U
    
' Funzionalità base (Guest)
usecase "Effettuare Login" as UC1
usecase "Filtrare elenco" as UC5
usecase UC8 as "Visualizzare Elenco Issues
--
**extension points**
Ordinare Elenco"

' Funzionalità operative (Utente)
usecase UC2 as "Segnalare Issue
--
**extension points**
Segnalare Priorità
Allegare Immagine
Specificare Tipologia"

usecase "Assegnare Etichette" as UC3
usecase "Aggiornare Stato Issue" as UC4
usecase "Assegnare issue" as UC6
usecase "Esportare Elenco Issue" as UC7

' Funzionalità amministrative (Admin)
usecase "Creare Nuovo Utente" as UC_A1
usecase "Generare Report" as UC_A2

' Dettagli tecnici
usecase "Aggiungere Titolo" as UC_INC1
usecase "Aggiungere Descrizione" as UC_INC2
usecase "Segnalare Priorità" as UC_EXT1
usecase "Allegare Immagine" as UC_EXT2
usecase "Specificare Tipologia" as UC_EXT3
usecase "Ordinare Elenco" as UC_EXT4


' --- Associazioni ---

' Il Guest (e di conseguenza Utente e Admin) può fare queste azioni
G -- UC1
G -- UC8
G -- UC5

' L'Utente (e l'Admin) aggiunge queste azioni
U -- UC2
U -- UC3
U -- UC4
U -- UC6
U -- UC7

' L'Admin aggiunge queste azioni specifiche
A -- UC_A1
A -- UC_A2

' Relazioni di sistema
UC2 ..> UC_INC1 : <<Include>>
UC2 ..> UC_INC2 : <<Include>>
UC_EXT1 ..> UC2 : <<Extend>>
UC_EXT2 ..> UC2 : <<Extend>>
UC_EXT3 ..> UC2 : <<Extend>>
UC_EXT4 ..> UC8 : <<Extend>>

@endum